import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [open,setOpen] = React.useState("C")
  const [location, setLocation] = React.useState("")
  const [active, setActive] = React.useState("")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ width : "280px", borderBottom : "1px solid gray",  }}>
        <div style={{ position : 'relative', display : "flex", flexDirection : "column" }} className="tabs-wrapper">
          <div>
             <button onClick={() => {
          setOpen("C")
          setLocation("line_club")
          console.log(location)
        }} 
        className="btn tabs">Club</button>
        <button onClick={() => {
          setOpen("C")
          setLocation("line_gold")
        }}  className="btn tabs">Gold</button>
        <button onClick={() => {
          setOpen("G")
          setLocation("line_premium")
        }} 
         className="btn tabs">Premium</button>
        <button onClick={() => {
          setOpen("P")
          setLocation("line_diamond")
        }} 
         className="btn tabs">Diamond</button>
          </div>
          <div style={{ border : "1px solid black", width : "60px", position : "absolute", bottom : "0px","left" : "0" }} className={location}></div>
        </div>
        <button onClick={()=> {
          active == "C" ? setActive("D") : setActive("C")
          console.log(active)
        }} style={{ width : "200px", borderBottom : "1px solid grey", display : "flex" }} >
            <p>открыть <span> > </span></p>
        </button>
        <div style={{ border : "1px solid grey", width : "200px" ,height : "0px", transitionDuration : "0.3s", backgroundColor : "grey" }} className={active == "C" ? "active" : ""}></div>
        </div>
      </main>
    </div>
  )
}
